apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: horizon-bot-homepage-image-updater
  namespace: horizon-bot
spec:
  namespace: argocd
  writeBackConfig:
    method: argocd
  applicationRefs:
    - namePattern: horizon-bot-docs
      images:
        - alias: horizon-bot-homepage
          imageName: ghcr.io/horizon-tempvoice/horizon-homepage:latest
          commonUpdateSettings:
            updateStrategy: digest
