apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: horizon-bot-homepage
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
    external-dns.alpha.kubernetes.io/target: lb-fsn-1.diamondforge.me
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_clear_headers "X-Frame-Options";
      more_set_headers "Content-Security-Policy: frame-ancestors https://top.gg";
spec:
  ingressClassName: nginx-ic
  tls:
  - hosts:
    - horizon-bot.me
    secretName: horizon-bot-homepage-tls
  rules:
  - host: horizon-bot.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: horizon-bot-homepage
            port:
              number: 80
