apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: horizon-bot-docs-path
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - horizon-bot.me
    secretName: horizon-bot-homepage-tls
  rules:
  - host: horizon-bot.me
    http:
      paths:
      - path: /docs
        pathType: Prefix
        backend:
          service:
            name: horizon-bot-docs
            port:
              number: 80
